### ISSUE TITLE
Temporary password bug

### ISSUE THREAD

**Issue by kayront** [LedgerHQ/app-monero#65] opened 2020-06-08 07:54 UTC
When using a temporary password, and after the device is automatically inactivity-locked, entering the correct pin will result in the wrong XMR address being displayed, and the Monero wallet begins malfunctioning too.

Haven't had the opportunity to test that this has been fixed in 1.6.0, but probably not.

**Comment by grydz** [comment] 2020-06-08 09:57
What's the version of the Monero app and the Monero client (specify if CLI or GUI)?

**Comment by kayront** [comment] 2020-06-08 18:26
1.4.2 / 0.15

**Comment by grydz** [comment] 2020-06-09 07:48
The Monero app version `1.4.2` has been released more than 7 months ago and I'm not able to reproduce the issue with version `1.6.0`.

If you have a completely different address, be sure to have configured the network you want: `mainnet`, `stagenet` or `testnet` in both the Monero wallet (before opening the wallet: Advanced options / Change Network) and the Monero app (Settings / Select Network).

Could you update the Monero app and the Monero client to confirm the bug?

**Comment by grydz** [comment] 2020-07-02 11:36
I'm closing the issue.

Feel free to open a new issue if you still have the bug after updating the app and the client.

**Closed by grydz** 2020-07-02 11:36 UTC
